# Minimal fix to proxy /api/* to Render (keeps your SPA and headers intact)
[build]
  command = "npm run build"
  publish = "dist"

# PROXY: send /api/* to your Render backend
[[redirects]]
  from = "/api/*"
  to = "https://fixed-income-mvp-backend.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers (same as your logs)
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
